### ISSUE TITLE
Defer native compilation to the end user

### ISSUE THREAD

**Issue by saantiaguilera** [saantiaguilera/android-api-SecureKeys#14]
### Description

Currently, the only 'cons' of this library is that it has to send configurations and keys enctrypted over java (because `.so` is generated in the aar). This could be easily avoided (and be far more secure) if the native compilation could be deferred to the end user (this way all keys/configurations/etc could be enctryped inside the `.so` instead of in a `.java` class, and be harder to detect), the problem is that theres no support for this given by android/gradle, so we should do it on our own completely.

### Solution

We need to basically create a gradle plugin for the user to extract from the `.aar` the native classes, add the configuration to its repository configuring it for NDK buildage. The apt should start creating c++ headers instead of java classes.

### Additional Information

Some (although extremely few) have also found this issue (mostly in google vr), so this links might be useful:
- **https://github.com/googlesamples/android-ndk/issues/261**
- https://stackoverflow.com/questions/35140809/android-aar-package-for-native-library/43661627#43661627
- https://github.com/googlesamples/android-ndk/issues/238

**Comment by MEiDIK** [comment]
Great Job！
