### ISSUE TITLE
Disadvantages to using this library

### ISSUE THREAD

**Issue by qazt482** [saantiaguilera/android-api-SecureKeys#25]
You may want to address some of the comments on Reddit:

https://www.reddit.com/r/androiddev/comments/6kwgdb/keeping_data_safe_in_android/

**Comment by saantiaguilera** [comment]
Thanks, I have answered all the ambiguous ones (since some answeres were `reading this I can see this is really easy to crack.` but it doesnt explain me how its easy :(.

As Im getting information I will be creating issues for each of them separately

Thanks! :)
