### ISSUE TITLE
support.annotations Gradle dependency collision

### ISSUE THREAD

**Issue by paramsen** [saantiaguilera/android-api-SecureKeys#31]
### Description

Created new project from template in AS, added dependencies, built project - it fails with the following message `Error:Failed to resolve: com.android.support:support-annotations:25.4.0`.

### Reproduction

Create new project from template, follow wiki/setup.

### Solution

It's something _wrong_ with how the `support.annotation` is included in the `:core` module, I haven't checked what. In order to solve it, exclude `support.annotation` like this:

```groovy
compile ("com.saantiaguilera.securekeys:core:2.0.1", {
  exclude group: 'com.android.support', module: 'support-annotations'
})
```

### Additional Information

* Dependency version: 2.01
* Dependencies used: std test libs, `com.android.support:appcompat-v7:25.3.1`
* Platform version: 2.3.2

**Comment by saantiaguilera** [comment]
Oh sorry, thats because from 25.4.0 onwards (26.0.0, etc) google has migrated to maven. I'll change it to 25.3.0 for the next release, for now you can:
1. Exclude it as you have done
2. Force another annotation version
```gradle
dependency {
  compile ("com.android.support: support-annotations:25.3.1") { // Or the version you want
    force = true
  }
}
```
3. Add the maven lookup of google for using 25.4.0
```
// In the root build.gradle
allprojects {
  repositories {
    jcenter()
    maven {
      url "https://maven.google.com"
    }
  }
}
```

**Comment by paramsen** [comment]
Cool, good to know, might bump into this with other dependencies when I get back from my vacation 👍
