### ISSUE TITLE
Already using externalNativeBuild in the defaultbuild and in the main section of build.gradle

### ISSUE THREAD

**Issue by BobString** [saantiaguilera/android-api-SecureKeys#42]
### Description

I tried to add the library to my project, but because I am already using the externalNativeBuild for another library and when gradle compiles it gives me:
`Error:More than one externalNativeBuild path specified`

### Reproduction

Have a externalNativeBuild section in the gradle file.

### Solution

Maybe the method addNativeBuildingSupport from [android-api-SecureKeys/plugin/src/main/groovy/com/saantiaguilera/securekeys/gradle/NativePackagerPlugin.groovy](https://github.com/saantiaguilera/android-api-SecureKeys/blob/master/plugin/src/main/groovy/com/saantiaguilera/securekeys/gradle/NativePackagerPlugin.groovy) should be optional and add that configurations manually along the original externalNativeBuild.

Or check if externalNativeBuild already exist in the gradle file, do nothing.

**Comment by saantiaguilera** [comment]
Im gonna be off for a month, gonna try to fix it as soon as im back :)

If you can open a PR fixing it tho, I will gladly review/merge it :)

**Comment by saantiaguilera** [comment]
Hey, I've been testing this and gradle doesnt support the -D argument for providing more than one CMake (eg /path/to/first/CMakeLists.txt;/path/to/second/CMakeLists.txt). So what Im doing is:

- If I find already a CMake path provided, I will halt the gradle op. and tell you to customize a root CMake with mine too (and I provide you in the description the path to my CMake, so no need to copy the file or do nasty things). This is at least what android gives as support for multiple CMakes https://developer.android.com/studio/projects/add-native-code.html.
- You have to declare an extension to disable this autoCompilation. Like this:
```gradle
// At the end of your module build.gradle
ext.autoCompileSecureKeys = false
apply plugin: 'saantiaguilera.securekeys'
```

And thats it :), just tested it with samples from the ndk-samples of android and it works.

**Note that this only applies to native modules.**
