### ISSUE TITLE
Impossible to add to new project

### ISSUE THREAD

**Issue by pcegarra** [saantiaguilera/android-api-SecureKeys#43]
Im using Android study canary 8 with gradle 3.0.0-alpha8.

Error:Gradle project cmake.path is /me/Demo2/app/build/secure-keys/include/main/cpp/CMakeLists.txt but that file doesn't exist

I need to create a project with c++ support, right?

Then, with support c++ Im getting this error:

`                                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/base.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_dependencies_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_0_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_1_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_2_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_3_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_4_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_5_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_6_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_7_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_8_apk.apk", zip file "/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/base.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/eu.costaoeste.demo3-0vq6oVujoMytS3FRMZITyg==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libsecure-keys.so"`

**Comment by pcegarra** [comment]
When I add this library to my gradle a new empty folder called cpp is created on my /app, and then the error cpp/CMakeLists.txt file doenst exists

**Comment by saantiaguilera** [comment]
Possibly related to https://github.com/saantiaguilera/android-api-SecureKeys/issues/40

**Comment by saantiaguilera** [comment]
Closing issue, fix can be seen in version: 2.2.0

**Comment by RehmanMuradAli** [comment]
I have added this library to my gradle. showing this error:
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tez.androidapp.uat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.tez.androidapp.uat-1/lib/arm, /data/app/com.tez.androidapp.uat-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libsecure-keys.so"

**Comment by RehmanMuradAli** [comment]
After adding v2.2.0 to my gradle. This shows:
java.lang.UnsatisfiedLinkError: 
dalvik.system.PathClassLoader[
	DexPathList[[zip file "/data/app/.../base.apk"],
	nativeLibraryDirectories=[/data/app/.../lib/arm, 
	/data/app/.../lib/armeabi-v7a, 
	/vendor/lib, /system/lib]]] 
couldn't find "libsecure-keys.so"
