### ISSUE TITLE
saantiaguilera.securekeys dynamic library?

### ISSUE THREAD

**Issue by nndnnv** [saantiaguilera/android-api-SecureKeys#54]
Hi,

thanks for writing this great library.
Can you please explain what is the job of
apply plugin: 'saantiaguilera.securekeys'
in testApp and core modules, I guess         
`
classpath` "com.saantiaguilera.securekeys:plugin:$libraryDynamicVersion"
`
is downloading this library and applying it? (my guess, dynamic library? :)
what is the job of this library? is there any chance that we will download this library and use it local?
can i guess SecureKeys without this library?
when i tried to remove it, i got runtime exception of 'secure-keys.so' file not found.

thanks

**Comment by saantiaguilera** [comment]
Hey! "kind of". The idea of the plugin is to unpack the native code since the one building the `.so` are the developers and not this library (as I can't inject your constants into my `.so` files) :)

So yeah, you could say it's a """""dynamic library"""""".
