### ISSUE TITLE
Gradle project cmake.path is ...\app\build\secure-keys\include\main\cpp\CMakeLists.txt but that file doesn't exist

### ISSUE THREAD

**Issue by jrcacd** [saantiaguilera/android-api-SecureKeys#55]

**Comment by saantiaguilera** [comment]
I think this is the main issue everyone has, which I can't fix as long as the gradle plugin of android has the "sync" and "build" button not triggering the unpackager of the plugin. If you really need a whitebox solution I suggest using [this library](https://github.com/MEiDIK/Cipher.so) as it's the same logic behind this one but the user mantains it
