### ISSUE TITLE
Encryption key is embedded in the application and very easy to retreive

### ISSUE THREAD

**Issue by max-r-b** [saantiaguilera/android-api-SecureKeys#56]
### Description

The key used to encrypt the secret is embedded in the app and can be easily retrieved.

The key and IV are generated using only printable characters (which is very weak and reduce the entropy, but this is an other matter).

In SecureKeyProcessor.java
```java
                    String seedString = Encoder.hash(String.valueOf(System.nanoTime()));
                    byte[] seed = seedString.getBytes(Charset.forName("UTF-8"));

                    // Create iv from start and key from end in reverse
                    for (int i = 0 ; i < 32 ; i++) {
                        if (i < 16) {
                            iv[i] = seed[i];
                        }
                        key[i] = seed[seed.length - i - 1];
                    }
```
In Encoder.java
```java
public static String hash(String name) {
        try {
            MessageDigest m = MessageDigest.getInstance(hash);
            m.update(name.getBytes(Charset.forName(utf8)));
            byte[] digest = m.digest();
            BigInteger bigInt = new BigInteger(1, digest);
            return bigInt.toString(STRING_RADIX_REPRESENTATION);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
```
It means that you will have to look for strings in the binary which makes it quite easy to find.
Also the key and IV are stored as initial values as objects member.
In configurations.cpp
```java
unsigned char Configurations::aes_iv[AES_IV_SIZE] = SECUREKEYS_AES_INITIAL_VECTOR;
unsigned char Configurations::aes_key[AES_KEY_SIZE] = SECUREKEYS_AES_KEY;
```
In ELF file generated with clang those values are stored in the .data section.

### Reproduction

You first need to unzip the APK to exctract the so file.

```bash
$ readelf -p .data  lib/armeabi/libsecure-keys.so
  [     5]  /�B�D7q�������[�V9�^Q�Y��?��^^\���^G�^A[�^R��1$�}^LUt]�r��ާ^F�t����i���G����^O�^L$o,�-��tJܰ\��vRQ>�m�1��'^C��^�Y��^K��G���Qc�^Fg))^T�^J�'8!^[.�m,M^S^M8STs^Je�^Jjv.�
,r���Kf^Z�p�K�Ql�^Y���$^F��5^N�p�j^P^V��^Y^Hl7^^LwH'���4�^L^\9J��NO�[�o.h�toc�x^Tx�^H^B������lP������xq�bbc671d98ca126235dd7d5255969c1df598d27aab1350733
...
```

We can clearly identify a string here: _bbc671d98ca126235dd7d5255969c1df598d27aab1350733_. This is the IV followed by the key as declared in configuration.cpp.
```
iv = bbc671d98ca12623 = 62626336373164393863613132363233
key = 5dd7d5255969c1df598d27aab1350733 = 3564643764353235353936396331646635393864323761616231333530373333
```

Then it is easy to decrypt the secrets, you retrieve the lookup table in the .rodata section.
```bash
$ readelf -p .rodata  lib/armeabi/libsecure-keys.so | less
String dump of section '.rodata':
  [     0]  Already initialized
  [    14]  c9046f7a37ad0ea7cee73355984fa5428982f8b37c8f7bcec91f7ac71a7cd104
  [    55]  HYcfqu9FVrGoRBDNnyLQxEg6xbSULi1T6Y3JLN95LhDIDTRtZbMDRGQgOE1b8y21
...
```
To finish you can decrypt the secret using openssl or whatever
```bash
$ echo "HYcfqu9FVrGoRBDNnyLQxEg6xbSULi1T6Y3JLN95LhDIDTRtZbMDRGQgOE1b8y21" |openssl base64 -d | openssl enc -aes-256-cbc -d -K 3564643764353235353936396331646635393864323761616231333530373333 -iv 626236633137396463383161363233
```

### Solution

Sadly, there is no solution I recommend. Developers should avoid to embed secret keys in their application. The problem you try to solve is actively researched and is called [whitebox cryptography](https://crypto.stackexchange.com/questions/386/what-are-the-differences-between-white-box-cryptography-and-code-obfuscation). Some solutions try to replace AES implementation and a key by a huge lookup table. However all the public proposal have been broken...

In the meantime, you can try to better hide the key. Here are some ideas:
1. Avoid using string to represent you key and IV (and use true randomness for their generation, they should be indistinguishable from random).
2. Use a different IV for each secret encryption
3. You can try to store it in the an other section (using _\_attribute_\_((section(".text"))) for example). Why not changing the section between builds.
4. You can try to hide the key in the .text area among code

**Comment by saantiaguilera** [comment]
Hey, sorry for not answering in such a long time. Yeah, I know it's still easy to find them, the idea of this library (although I don't mantain it anymore) was to have a whitebox solution for people that can't afford a backend (since storing them in plain text or as a resource is far easier to find). [I had written that in the moment I made the wiki, so beginners don't think this is a magical savior and the way to go](https://github.com/saantiaguilera/android-api-SecureKeys/wiki#securekeys)

Still, thanks for taking the time to write this and everything :)
