### ISSUE TITLE
Failed to resolve annotationProcessor

### ISSUE THREAD

**Issue by pcegarra** [saantiaguilera/android-api-SecureKeys#6]
Im trying to use this awesome library on my new project but Im having some problemens importing it with gradle.

How can I use it with annotationProcessor instead apt?

```
Error:(58, 0) Gradle DSL method not found: 'apt()'
Possible causes:<ul><li>The project '*' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.3 and sync project</a></li><li>The project '*' may be using a version of Gradle that does not contain the method.
<a href="openGradleSettings">Gradle settings</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
```

**Comment by saantiaguilera** [comment]
Oh, my bad! I forgot to add it to the `README` (will do, thanks!)

I use `classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'` and `apply plugin: 'android-apt'` for using `apt`, but this is deprecated in newer gradle plugins for `annotationProcessor`. Simply use it with:
```gradle
annotationProcessor "com.saantiaguilera.securekeys:processor:<version>"
```

Tell me if it works :)
